language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'nightly'
os:
  - linux
jobs:
  fast_finish: true
  allow_failures:
    - python: 'nightly'
install: pip install tox-travis
script: tox
